import { ScenarioSchema, type ScenarioDefinition, type ScenarioInput } from './schema';

/**
 * Built-in scenario library. Every scenario is plain data composed from
 * pathology modules and validated by the same schema used for AI-generated
 * scenarios. Titles/taglines are deliberately non-diagnostic.
 */
const RAW: ScenarioInput[] = [
  {
    id: 'found-unresponsive',
    title: 'Found unresponsive',
    tagline: 'Unknown adult found unresponsive in a public restroom',
    category: 'toxicology',
    difficulty: 2,
    hiddenDiagnosis: 'Opioid (heroin) toxicity with respiratory depression',
    diagnosisKeywords: ['opioid', 'opiate', 'heroin', 'overdose', 'narcotic'],
    differentials: ['Hypoglycaemia', 'Head injury', 'Alcohol intoxication', 'Stroke', 'Post-ictal state'],
    patient: { ageRange: [20, 45], sex: 'any', bmiRange: [18, 26], social: { drugs: 'opioids', smoking: 'current' }, unknownIdentity: true, requiredHistory: ['opioidUseDisorder'] },
    presentation: {
      handoff:
        'Unknown {sex}, approximately {age}, found slumped on the floor of a public restroom by a cleaner about 15 minutes ago. Snoring respirations on our arrival, slow breathing. No ID, no witnesses. We have not given any medications. No obvious trauma.',
      chiefComplaint: 'Unresponsive',
      prehospital: { oxygen: 'nonRebreather', oxygenFlow: 15, ivAccess: false, cprInProgress: false, bvm: false, tourniquet: null },
    },
    pathologies: [{ type: 'opioidToxicity', params: { agent: 'heroin', doseMg: 15, route: 'IV' }, onsetMinutesBeforeArrival: 14 }],
    patientKnowledge: {
      story: 'Injected heroin in the restroom. Has used heroin daily for years; this batch was "stronger than usual". Would be embarrassed and initially minimise drug use.',
      symptoms: ['sleepy', 'nauseated', 'itchy'],
      ifAsked: ['Uses heroin most days', 'Last used in the restroom', 'Has been to rehab once', 'No other medical problems'],
      conceals: ['Initially denies drug use unless asked directly and kindly'],
      personality: 'guarded, irritable if woken abruptly',
    },
    authoredFindings: { exam: [{ zone: 'arms', finding: 'Multiple needle track marks in both antecubital fossae' }] },
    learningObjectives: [
      'Recognise the opioid toxidrome (reduced consciousness, respiratory depression, miosis)',
      'Prioritise airway and ventilation before antidote',
      'Titrate naloxone to adequate ventilation rather than full arousal',
      'Anticipate re-sedation because naloxone is shorter-acting than many opioids',
    ],
    keyEvidence: ['Pinpoint pupils', 'Respiratory rate < 8', 'Rising PaCO2 / EtCO2', 'Track marks', 'Response to naloxone'],
    debriefNotes: ['In this simulator naloxone is a competitive μ-receptor antagonist: small doses shift the opioid concentration–effect curve; large doses in a dependent patient precipitate withdrawal and agitation.'],
  },
  {
    id: 'cant-breathe',
    title: 'Short of breath',
    tagline: 'Young adult brought in by ambulance struggling to breathe',
    category: 'respiratory',
    difficulty: 3,
    hiddenDiagnosis: 'Severe acute asthma progressing to life-threatening asthma',
    diagnosisKeywords: ['asthma', 'bronchospasm', 'status asthmaticus'],
    differentials: ['Anaphylaxis', 'Pneumothorax', 'Pneumonia', 'Panic attack', 'Upper airway obstruction'],
    patient: { ageRange: [16, 35], sex: 'any', requiredHistory: ['asthma'], forbiddenHistory: ['copd', 'heartFailure', 'cad'] },
    presentation: {
      handoff:
        '{age}-year-old {sex}, known asthmatic, woke up breathless two hours ago with a cold for the past few days. Used {pronoun} blue inhaler about 20 times without relief. Speaking in short phrases. Tripoding on the stretcher. Tried oxygen by mask en route.',
      chiefComplaint: "Can't breathe",
      prehospital: { oxygen: 'simpleMask', oxygenFlow: 8, ivAccess: false, cprInProgress: false, bvm: false, tourniquet: null },
    },
    pathologies: [{ type: 'asthma', params: { severity: 0.62, progression: 0.35, trigger: 'viral upper respiratory infection' }, onsetMinutesBeforeArrival: 100 }],
    patientKnowledge: {
      story: 'Had a cold for 4 days. Chest getting tighter since yesterday; woke at 3am unable to breathe. Used salbutamol inhaler repeatedly with little effect. Previously admitted to ICU once, aged 16. Stopped taking the brown (steroid) inhaler months ago.',
      symptoms: ['tight chest', 'cannot catch breath', 'exhausted', 'frightened'],
      ifAsked: ['Previous ICU admission for asthma', 'Not taking preventer inhaler', 'No known drug allergies', 'Lives with a cat'],
      conceals: [],
      personality: 'terrified, answers in short phrases',
    },
    learningObjectives: [
      'Assess asthma severity (speech, SpO2, peak flow proxy, silent chest, exhaustion)',
      'Deliver nebulised bronchodilators and systemic steroids early',
      'Escalate to IV magnesium / adrenaline for life-threatening features',
      'Recognise that a normal or rising PaCO2 in acute asthma signals fatigue',
    ],
    keyEvidence: ['Widespread wheeze → quiet chest', 'Rising PaCO2', 'Accessory muscle use', 'Hypoxaemia'],
    debriefNotes: ['Nebulised drug delivery in this simulator scales with airflow — with very poor ventilation, less drug reaches the airways.', 'Rapid bag ventilation causes air trapping (auto-PEEP), raising intrathoracic pressure and lowering blood pressure.'],
  },
  {
    id: 'swelling-after-dinner',
    title: 'Itchy and breathless',
    tagline: 'Adult became unwell at a restaurant',
    category: 'respiratory',
    difficulty: 2,
    hiddenDiagnosis: 'Anaphylaxis (food, peanut) with airway oedema and distributive shock',
    diagnosisKeywords: ['anaphylaxis', 'anaphylactic', 'allergic reaction', 'allergy'],
    differentials: ['Asthma', 'Angioedema (ACE-inhibitor)', 'Panic attack', 'Scombroid poisoning', 'Septic shock'],
    patient: { ageRange: [18, 50], sex: 'any', requiredHistory: ['peanutAllergy'], allergies: [{ agent: 'Peanuts', reaction: 'anaphylaxis' }] },
    presentation: {
      handoff:
        '{age}-year-old {sex} who started feeling unwell 10 minutes after eating at a Thai restaurant. Itchy, hoarse voice, feels like {pronoun} throat is tight. Rash on the chest. Did not have {pronoun} auto-injector. Last BP in the ambulance was low.',
      chiefComplaint: 'Throat feels tight',
    },
    pathologies: [{ type: 'anaphylaxis', params: { allergen: 'peanut', severity: 0.9, exposure: 'ingested' }, onsetMinutesBeforeArrival: 9 }],
    patientKnowledge: {
      story: 'Ate a satay dish; told the waiter about the peanut allergy but thinks the sauce contained peanut. Lips tingled, then itching, then throat tightness and feeling faint.',
      symptoms: ['itchy all over', 'throat tight', 'hoarse voice', 'dizzy', 'stomach cramps'],
      ifAsked: ['Known peanut allergy since childhood', 'Previous reaction treated with adrenaline aged 12', 'Forgot the auto-injector at home', 'Mild asthma as a child'],
      conceals: [],
      personality: 'anxious, sense of impending doom',
    },
    learningObjectives: [
      'Recognise anaphylaxis from multi-system involvement',
      'Give IM adrenaline early (anterolateral thigh) and repeat as needed',
      'Understand why antihistamines do not treat airway oedema or shock',
      'Prepare for a difficult airway as oedema progresses',
    ],
    keyEvidence: ['Urticaria/flushing', 'Stridor / hoarseness', 'Wheeze', 'Hypotension with tachycardia'],
    debriefNotes: ['IM absorption in this simulator depends on peripheral perfusion — in profound shock, IM adrenaline is absorbed more slowly.', 'Adrenaline β2 effects also stabilise mast cells and reduce further mediator release.'],
  },
  {
    id: 'stab-wound-leg',
    title: 'Penetrating injury',
    tagline: 'Adult with a leg wound after an assault',
    category: 'trauma',
    difficulty: 2,
    hiddenDiagnosis: 'Haemorrhagic shock from a femoral vessel injury (compressible haemorrhage)',
    diagnosisKeywords: ['haemorrhage', 'hemorrhage', 'bleeding', 'hemorrhagic shock', 'haemorrhagic shock', 'hypovolaemic', 'hypovolemic', 'femoral'],
    differentials: ['Tension pneumothorax', 'Neurogenic shock', 'Vasovagal syncope'],
    patient: { ageRange: [18, 40], sex: 'any', forbiddenHistory: ['heartFailure'] },
    presentation: {
      handoff:
        '{age}-year-old {sex} stabbed in the left thigh about 15 minutes ago. Large pool of blood at scene. We applied a dressing; it has soaked through. {Pronoun} is pale and getting drowsy. No other injuries seen.',
      chiefComplaint: 'Stabbed in the leg',
    },
    pathologies: [{ type: 'hemorrhage', params: { site: 'leftThigh', rateMlMin: 90, priorLossMl: 450, mechanism: 'stab wound, left thigh' }, onsetMinutesBeforeArrival: 12 }],
    patientKnowledge: {
      story: 'Was attacked outside a bar and stabbed once in the left thigh with a knife. Felt warm blood pouring out. Now feels cold, thirsty and faint.',
      symptoms: ['pain in left thigh', 'thirsty', 'cold', 'dizzy', 'nauseous'],
      ifAsked: ['No medical problems', 'No medications', 'Had two beers tonight', 'Tetanus status unknown'],
      conceals: [],
      personality: 'scared, becoming confused as blood loss continues',
    },
    learningObjectives: [
      'Control catastrophic external haemorrhage first (tourniquet)',
      'Recognise class III haemorrhage from HR, pulse pressure, mentation',
      'Prefer blood products over large volumes of crystalloid',
      'Recognise the lethal triad (hypothermia, acidosis, coagulopathy)',
    ],
    keyEvidence: ['Active bleeding from thigh wound', 'Tachycardia, narrow pulse pressure', 'Delayed capillary refill', 'Falling Hb after resuscitation'],
    debriefNotes: ['Haemoglobin in this simulator is initially near-normal after acute bleeding and falls as plasma is refilled from the interstitium or crystalloid is given.', 'Cold blood products and crystalloid lower core temperature; hypothermia and acidosis reduce clot efficacy.'],
  },
  {
    id: 'rta-abdomen',
    title: 'Road traffic collision',
    tagline: 'Driver in a high-speed collision, complaining of abdominal pain',
    category: 'trauma',
    difficulty: 4,
    hiddenDiagnosis: 'Intra-abdominal haemorrhage (splenic injury) — non-compressible haemorrhage',
    diagnosisKeywords: ['splenic', 'spleen', 'intra-abdominal', 'intraabdominal', 'haemoperitoneum', 'hemoperitoneum', 'abdominal bleeding', 'internal bleeding'],
    differentials: ['Pelvic fracture', 'Tension pneumothorax', 'Cardiac tamponade', 'Spinal cord injury'],
    patient: { ageRange: [20, 60], sex: 'any' },
    presentation: {
      handoff:
        '{age}-year-old {sex}, restrained driver, T-boned at about 60 km/h, approximately 35 minutes ago. Complaining of left-sided abdominal and shoulder-tip pain. GCS 15 at scene. Heart rate has been climbing on the way in. Seatbelt mark across the abdomen.',
      chiefComplaint: 'Abdominal pain after a crash',
    },
    pathologies: [{ type: 'hemorrhage', params: { site: 'abdomen', rateMlMin: 45, priorLossMl: 600, mechanism: 'blunt abdominal trauma (splenic laceration)' }, onsetMinutesBeforeArrival: 30 }],
    patientKnowledge: {
      story: 'Car was hit on the driver side. Hit the steering wheel/seatbelt hard. Pain in the left upper abdomen and left shoulder tip.',
      symptoms: ['left upper abdominal pain', 'left shoulder pain', 'dizzy when sitting up', 'thirsty'],
      ifAsked: ['Takes no regular medications', 'No allergies', 'Last ate lunch 3 hours ago'],
      conceals: [],
      personality: 'stoic, understates pain',
    },
    authoredFindings: { exam: [{ zone: 'abdomen', finding: 'Seatbelt bruise across the lower abdomen; left upper quadrant tenderness with guarding' }], ctAbdomen: 'Grade IV splenic laceration with active arterial extravasation and moderate haemoperitoneum.' },
    learningObjectives: [
      'Recognise non-compressible torso haemorrhage',
      'Use FAST to identify intraperitoneal free fluid',
      'Activate definitive haemorrhage control early (surgery/IR)',
      'Apply permissive hypotension and haemostatic resuscitation',
    ],
    keyEvidence: ['Positive FAST', 'Rising lactate', 'Tachycardia with narrowing pulse pressure', 'Transient response to fluids'],
    debriefNotes: ['Raising blood pressure aggressively in this simulator increases bleeding rate and can dislodge an early clot.'],
  },
  {
    id: 'motorbike-chest',
    title: 'Motorcycle crash',
    tagline: 'Motorcyclist brought in with chest pain and breathlessness',
    category: 'trauma',
    difficulty: 3,
    hiddenDiagnosis: 'Right tension pneumothorax (obstructive shock)',
    diagnosisKeywords: ['tension pneumothorax', 'pneumothorax', 'tension'],
    differentials: ['Haemothorax', 'Cardiac tamponade', 'Haemorrhagic shock', 'Flail chest'],
    patient: { ageRange: [18, 45], sex: 'any' },
    presentation: {
      handoff:
        '{age}-year-old {sex}, motorcyclist, came off at speed about 10 minutes ago and hit a barrier with the right side of the chest. Increasingly short of breath in the ambulance, sats dropping despite oxygen. Right-sided chest pain.',
      chiefComplaint: 'Chest pain, cannot breathe',
      prehospital: { oxygen: 'nonRebreather', oxygenFlow: 15, ivAccess: true, cprInProgress: false, bvm: false, tourniquet: null },
    },
    pathologies: [{ type: 'tensionPneumothorax', params: { side: 'right', leakMlMin: 120, initialAirMl: 600, traumatic: true }, onsetMinutesBeforeArrival: 8 }],
    patientKnowledge: {
      story: 'Lost control on a bend and hit the crash barrier with the right side of the chest. Sharp right chest pain, worse breathing in, getting more breathless.',
      symptoms: ['sharp right chest pain', 'short of breath', 'feels like dying'],
      ifAsked: ['No medical history', 'No allergies', 'Wearing a helmet, did not lose consciousness'],
      conceals: [],
      personality: 'agitated, air hungry',
    },
    authoredFindings: { exam: [{ zone: 'chest', finding: 'Abrasions and tenderness over the right lateral chest wall' }] },
    learningObjectives: [
      'Make a clinical diagnosis of tension pneumothorax without waiting for imaging',
      'Perform needle/finger decompression at an appropriate site',
      'Follow decompression with a chest drain',
      'Recognise that positive-pressure ventilation accelerates tension physiology',
    ],
    keyEvidence: ['Absent breath sounds right', 'Hyper-resonance right', 'Hypoxaemia, hypotension, distended neck veins', 'Tracheal deviation (late)'],
    debriefNotes: ['Chest wall thickness is generated per patient; a 5 cm catheter at the 2nd ICS may not reach the pleura in larger patients, while the 4th/5th ICS anterior axillary site is usually thinner.'],
  },
  {
    id: 'chest-pain-sweaty',
    title: 'Chest pain',
    tagline: 'Middle-aged adult with chest pain and sweating',
    category: 'cardiovascular',
    difficulty: 3,
    hiddenDiagnosis: 'Anterior ST-elevation myocardial infarction (proximal LAD occlusion)',
    diagnosisKeywords: ['stemi', 'myocardial infarction', 'heart attack', 'acute coronary', 'lad', 'anterior mi', 'mi'],
    differentials: ['Aortic dissection', 'Pulmonary embolism', 'Pericarditis', 'Oesophageal spasm'],
    patient: { ageRange: [45, 75], sex: 'male', requiredHistory: ['hypertension'], social: { smoking: 'current' } },
    presentation: {
      handoff:
        '{age}-year-old {sex}, central crushing chest pain radiating to the left arm that started 45 minutes ago while shovelling snow. Sweaty and nauseated. Smoker, on blood pressure tablets. We have not given anything yet.',
      chiefComplaint: 'Chest pain',
    },
    pathologies: [{ type: 'myocardialIschemia', params: { territory: 'lad', occlusion: 1, collateral: 0.08 }, onsetMinutesBeforeArrival: 45 }],
    patientKnowledge: {
      story: 'Was shovelling snow when crushing central chest pain started, spreading to the left arm and jaw. Feels sick and sweaty. Never had pain like this before.',
      symptoms: ['crushing central chest pain', 'pain into left arm and jaw', 'nausea', 'sweating', 'breathless'],
      ifAsked: ['Smokes 20 a day', 'Father had a heart attack at 55', 'Takes amlodipine', 'No allergies'],
      conceals: [],
      personality: 'frightened, grey and clammy',
    },
    learningObjectives: [
      'Obtain and interpret a 12-lead ECG within minutes',
      'Give antiplatelet therapy and analgesia; use oxygen only for hypoxaemia',
      'Activate primary PCI — reperfusion is time-critical',
      'Anticipate ventricular arrhythmia and cardiogenic shock',
    ],
    keyEvidence: ['ST elevation V1–V4', 'Rising troponin', 'Crackles if LV fails'],
    debriefNotes: ['Infarct size in this simulator accumulates with the duration and severity of ischaemia; reperfusion stops progression but does not reverse infarcted tissue.'],
  },
  {
    id: 'inferior-stemi',
    title: 'Epigastric pain and faintness',
    tagline: 'Older adult with epigastric discomfort and near-syncope',
    category: 'cardiovascular',
    difficulty: 4,
    hiddenDiagnosis: 'Inferior STEMI with right ventricular involvement (proximal RCA occlusion)',
    diagnosisKeywords: ['inferior stemi', 'inferior mi', 'rca', 'right ventricular infarction', 'rv infarct', 'stemi', 'myocardial infarction'],
    differentials: ['Peptic ulcer disease', 'Pancreatitis', 'Aortic dissection', 'Cholecystitis'],
    patient: { ageRange: [55, 80], sex: 'any', requiredHistory: ['type2Diabetes'] },
    presentation: {
      handoff:
        '{age}-year-old {sex} with an hour of epigastric "indigestion" and nausea, nearly fainted on standing. Known diabetic. Pale and clammy. BP was on the soft side.',
      chiefComplaint: 'Indigestion and dizziness',
    },
    pathologies: [{ type: 'myocardialIschemia', params: { territory: 'rca', occlusion: 1, collateral: 0.1 }, onsetMinutesBeforeArrival: 60 }],
    patientKnowledge: {
      story: 'Felt a heavy indigestion-like pain in the upper abdomen after lunch, then felt sick and nearly fainted in the kitchen.',
      symptoms: ['upper abdominal discomfort', 'nausea', 'light-headed', 'sweaty'],
      ifAsked: ['Type 2 diabetes on metformin', 'No chest pain before', 'Takes no blood thinners'],
      conceals: [],
      personality: 'polite, minimises symptoms',
    },
    learningObjectives: [
      'Consider ACS in atypical (epigastric) presentations, especially in diabetics',
      'Identify inferior ST elevation and suspect RV involvement',
      'Recognise preload dependence: nitrates may precipitate profound hypotension',
      'Support RV infarction with judicious fluid and early reperfusion',
    ],
    keyEvidence: ['ST elevation II, III, aVF', 'Hypotension with clear lung fields', 'Raised RAP / plethoric IVC', 'Bradycardia'],
    debriefNotes: ['RV output in this simulator depends strongly on venous return; venodilators reduce preload and can collapse output when the RV is ischaemic.'],
  },
  {
    id: 'fever-confused',
    title: 'Fever and confusion',
    tagline: 'Elderly adult sent in from home with fever and new confusion',
    category: 'infection',
    difficulty: 3,
    hiddenDiagnosis: 'Septic shock from urinary source (E. coli urosepsis)',
    diagnosisKeywords: ['sepsis', 'septic', 'urosepsis', 'uti', 'pyelonephritis', 'septic shock'],
    differentials: ['Pneumonia', 'Stroke', 'Delirium from medication', 'Hypoglycaemia', 'Meningitis'],
    patient: { ageRange: [70, 90], sex: 'female' },
    presentation: {
      handoff:
        '{age}-year-old {sex} brought in by {pronoun} daughter: two days of feeling unwell, today confused and not making sense. Hot to touch, shivering earlier. Not drinking much. Daughter mentioned {pronoun} has been going to the toilet a lot.',
      chiefComplaint: 'Confusion and fever',
    },
    pathologies: [{ type: 'sepsis', params: { source: 'urinary', organism: 'ecoli', burden: 0.45, growth: 0.3 }, onsetMinutesBeforeArrival: 300 }],
    patientKnowledge: {
      story: 'Has had burning when passing urine and going frequently for 3 days. Now feels hot and cold, weak, pain in the right side of the back. Muddled about the date.',
      symptoms: ['burning urine', 'right back pain', 'shivers', 'weak'],
      ifAsked: ['Allergies as documented', 'Lives alone', 'Takes blood pressure tablets'],
      conceals: [],
      personality: 'confused, answers slowly, sometimes off-topic',
    },
    authoredFindings: { urinalysis: 'Cloudy, offensive-smelling urine', bloodCulture: 'Gram-negative bacilli (later identified as E. coli) — reported after the case' },
    learningObjectives: [
      'Recognise sepsis with hypoperfusion (lactate, hypotension, altered mentation)',
      'Deliver early appropriate antibiotics after cultures',
      'Give fluid resuscitation and start vasopressors for persistent hypotension',
      'Check allergies before prescribing',
    ],
    keyEvidence: ['Fever, tachycardia, hypotension', 'Elevated lactate', 'Positive urinalysis', 'Rising creatinine'],
    debriefNotes: ['Capillary leak in this simulator increases with inflammation, so a larger fraction of crystalloid leaves the circulation in sepsis.'],
  },
  {
    id: 'cough-breathless',
    title: 'Cough and breathlessness',
    tagline: 'Adult with productive cough, fever and breathlessness',
    category: 'infection',
    difficulty: 3,
    hiddenDiagnosis: 'Severe community-acquired pneumonia (pneumococcal) with sepsis and hypoxaemic respiratory failure',
    diagnosisKeywords: ['pneumonia', 'sepsis', 'septic', 'cap', 'chest infection', 'lrti'],
    differentials: ['Pulmonary embolism', 'Heart failure', 'COVID-19', 'Asthma exacerbation'],
    patient: { ageRange: [45, 80], sex: 'any', social: { smoking: 'current' } },
    presentation: {
      handoff:
        '{age}-year-old {sex}, three days of productive cough, fevers and right-sided chest pain on breathing. Breathless on minimal exertion today. Sats low 90s on room air in the ambulance.',
      chiefComplaint: 'Cough, fever, breathless',
    },
    pathologies: [{ type: 'sepsis', params: { source: 'pneumonia', organism: 'strepPneumo', burden: 0.3, growth: 0.25 }, onsetMinutesBeforeArrival: 200 }],
    patientKnowledge: {
      story: 'Started with shivers and cough three days ago, now bringing up rusty sputum, sharp pain on the right when breathing in.',
      symptoms: ['cough with rusty sputum', 'right-sided chest pain on breathing', 'fever', 'breathless'],
      ifAsked: ['Smoker', 'No recent travel', 'No leg swelling'],
      conceals: [],
      personality: 'tired, breathless between sentences',
    },
    learningObjectives: ['Assess severity of pneumonia (e.g. CURB-65 concepts)', 'Provide titrated oxygen and early antibiotics', 'Recognise shunt physiology: hypoxaemia that responds incompletely to oxygen', 'Escalate respiratory support appropriately'],
    keyEvidence: ['Right basal crackles', 'Consolidation on CXR', 'Hypoxaemia', 'Raised WBC'],
    debriefNotes: ['Consolidation is modelled as intrapulmonary shunt, which responds only partially to supplemental oxygen; PEEP can recruit some of it.'],
  },
  {
    id: 'drowsy-diabetic',
    title: 'Vomiting and drowsy',
    tagline: 'Young adult with a day of vomiting, now drowsy and breathing fast',
    category: 'metabolic',
    difficulty: 3,
    hiddenDiagnosis: 'Diabetic ketoacidosis',
    diagnosisKeywords: ['dka', 'diabetic ketoacidosis', 'ketoacidosis'],
    differentials: ['Gastroenteritis', 'Sepsis', 'Salicylate toxicity', 'Alcoholic ketoacidosis', 'Appendicitis'],
    patient: { ageRange: [16, 32], sex: 'any', requiredHistory: ['type1Diabetes'], bmiRange: [18, 25] },
    presentation: {
      handoff:
        '{age}-year-old {sex} with a day of vomiting and abdominal pain, very thirsty, now drowsy. Breathing deep and fast. Flatmate says {pronoun} has "diabetes" but ran out of insulin a few days ago.',
      chiefComplaint: 'Vomiting and abdominal pain',
    },
    pathologies: [{ type: 'dka', params: { severity: 0.9 }, onsetMinutesBeforeArrival: 1440 }],
    patientKnowledge: {
      story: 'Type 1 diabetic since age 9. Ran out of insulin 3 days ago and could not afford a new prescription. Vomiting since yesterday, very thirsty, passing lots of urine, tummy pain.',
      symptoms: ['thirsty', 'vomiting', 'tummy pain', 'breathless', 'weak'],
      ifAsked: ['Ran out of insulin 3 days ago', 'Usually takes glargine and aspart', 'Previous DKA admission once'],
      conceals: ['Embarrassed about not affording insulin'],
      personality: 'drowsy, irritable',
    },
    learningObjectives: [
      'Diagnose DKA (hyperglycaemia, ketonaemia, metabolic acidosis)',
      'Prioritise fluid resuscitation',
      'Start fixed-rate insulin and replace potassium as it falls',
      'Recognise Kussmaul respiration as respiratory compensation',
    ],
    keyEvidence: ['Glucose > 20 mmol/L', 'Ketones > 3 mmol/L', 'pH < 7.2, low bicarbonate, raised anion gap', 'Deep rapid breathing'],
    debriefNotes: ['Potassium in this simulator shifts into cells with insulin; total body potassium is depleted in DKA, so serum K can fall rapidly without replacement.'],
  },
  {
    id: 'strange-behaviour',
    title: 'Strange behaviour',
    tagline: 'Adult found behaving oddly at home by a family member',
    category: 'metabolic',
    difficulty: 1,
    hiddenDiagnosis: 'Severe hypoglycaemia due to insulin overdose',
    diagnosisKeywords: ['hypoglycaemia', 'hypoglycemia', 'low blood sugar', 'insulin overdose', 'hypo'],
    differentials: ['Stroke', 'Intoxication', 'Psychosis', 'Seizure'],
    patient: { ageRange: [20, 60], sex: 'any', requiredHistory: ['type1Diabetes'] },
    presentation: {
      handoff:
        "{age}-year-old {sex} found by {pronoun} partner acting strangely, sweaty and slurring words about 30 minutes ago. Now barely responding. Partner thinks {pronoun} may have taken the wrong insulin pen last night. We couldn't get a glucometer reading — machine error.",
      chiefComplaint: 'Confused and sweaty',
    },
    pathologies: [{ type: 'hypoglycemia', params: { cause: 'insulinOverdose', insulinUnits: 50 }, onsetMinutesBeforeArrival: 150 }],
    patientKnowledge: {
      story: 'Type 1 diabetic. Last night may have injected a large dose of long-acting insulin by mistake. Skipped breakfast.',
      symptoms: ['shaky', 'sweaty', 'confused', 'hungry'],
      ifAsked: ['Type 1 diabetes', 'Takes glargine at night and aspart with meals', 'No allergies'],
      conceals: [],
      personality: 'confused, slurring, may be combative',
    },
    learningObjectives: ['Always check glucose in altered consciousness', 'Treat with IV dextrose (or IM glucagon without access)', 'Anticipate recurrent hypoglycaemia with long-acting insulin — start a dextrose infusion and monitor'],
    keyEvidence: ['Capillary glucose < 3 mmol/L', 'Diaphoresis and tremor', 'Rapid response to dextrose'],
    debriefNotes: ['The subcutaneous insulin depot keeps absorbing for many hours in the simulator, so glucose falls again after a single dextrose bolus.'],
  },
  {
    id: 'palpitations',
    title: 'Palpitations',
    tagline: 'Young adult with sudden-onset racing heart',
    category: 'cardiovascular',
    difficulty: 2,
    hiddenDiagnosis: 'Re-entrant supraventricular tachycardia (AVNRT)',
    diagnosisKeywords: ['svt', 'supraventricular tachycardia', 'avnrt', 'avrt', 're-entrant'],
    differentials: ['Atrial flutter', 'Ventricular tachycardia', 'Sinus tachycardia', 'Thyrotoxicosis', 'Panic attack'],
    patient: { ageRange: [18, 40], sex: 'any', requiredHistory: ['wpw'] },
    presentation: {
      handoff:
        '{age}-year-old {sex}, sudden onset of a racing heart 40 minutes ago while at work. Feels light-headed and a bit short of breath. Has had short episodes before that stopped on their own.',
      chiefComplaint: 'Heart racing',
    },
    pathologies: [{ type: 'arrhythmia', params: { kind: 'svt', rate: 205 }, onsetMinutesBeforeArrival: 40 }],
    patientKnowledge: {
      story: 'Heart suddenly started racing while sitting at the desk, like a switch. Pounding in the neck, light-headed. Previous short episodes stopped by themselves.',
      symptoms: ['heart racing', 'pounding in the neck', 'light-headed', 'mild chest tightness'],
      ifAsked: ['Several brief episodes before', 'No regular medications', 'Drank two coffees this morning'],
      conceals: [],
      personality: 'anxious but coherent',
    },
    learningObjectives: ['Identify a regular narrow-complex tachycardia', 'Attempt a vagal manoeuvre', 'Give adenosine as a rapid push with flush and warn the patient', 'Know when to cardiovert (instability)'],
    keyEvidence: ['Regular narrow-complex tachycardia ~200/min', 'Termination with adenosine'],
    debriefNotes: ['Adenosine has a plasma half-life of seconds in this simulator; slow injection or intraosseous delivery reduces the concentration reaching the AV node.'],
  },
  {
    id: 'dizzy-slow',
    title: 'Dizzy spells',
    tagline: 'Older adult with dizzy spells and fatigue',
    category: 'cardiovascular',
    difficulty: 3,
    hiddenDiagnosis: 'Complete (third-degree) heart block with symptomatic bradycardia',
    diagnosisKeywords: ['complete heart block', 'third degree', '3rd degree', 'chb', 'heart block', 'av block'],
    differentials: ['Sick sinus syndrome', 'Beta-blocker toxicity', 'Hyperkalaemia', 'Inferior MI'],
    patient: { ageRange: [68, 90], sex: 'any' },
    presentation: {
      handoff:
        '{age}-year-old {sex}, several dizzy spells today, one where {pronoun} nearly passed out getting up from a chair. Heart rate in the 30s on our monitor. Tired and a bit confused.',
      chiefComplaint: 'Dizzy and tired',
    },
    pathologies: [{ type: 'arrhythmia', params: { kind: 'chb' }, onsetMinutesBeforeArrival: 90 }],
    patientKnowledge: {
      story: 'Feeling increasingly tired for a few days, today several episodes of nearly blacking out.',
      symptoms: ['tired', 'light-headed', 'breathless on walking'],
      ifAsked: ['No new medications', 'No chest pain'],
      conceals: [],
      personality: 'slow to answer, pleasant',
    },
    learningObjectives: ['Recognise AV dissociation on the ECG', 'Understand why atropine may not work in infranodal block', 'Apply transcutaneous pacing with sedation/analgesia and confirm capture', 'Use a chronotropic infusion as a bridge'],
    keyEvidence: ['Rate ~35 with broad escape', 'P waves march through', 'Poor response to atropine'],
    debriefNotes: ['Atropine in this simulator removes vagal tone at the sinus/AV node but cannot accelerate a ventricular escape rhythm.'],
  },
  {
    id: 'collapsed-gym',
    title: 'Collapse at the gym',
    tagline: 'Adult collapsed while exercising — CPR in progress',
    category: 'cardiovascular',
    difficulty: 4,
    hiddenDiagnosis: 'Out-of-hospital cardiac arrest — ventricular fibrillation (ischaemic)',
    diagnosisKeywords: ['cardiac arrest', 'vf', 'ventricular fibrillation', 'ohca'],
    differentials: ['Hypertrophic cardiomyopathy', 'Pulmonary embolism', 'Hyperkalaemia', 'Commotio cordis'],
    patient: { ageRange: [40, 65], sex: 'male', requiredHistory: ['cad'] },
    presentation: {
      handoff:
        '{age}-year-old {sex} collapsed on a treadmill about 12 minutes ago. Bystander CPR within about a minute, then our crew with a mechanical CPR device. One shock given by a public AED. Still in cardiac arrest.',
      chiefComplaint: 'Cardiac arrest',
      prehospital: { oxygen: 'none', oxygenFlow: 0, ivAccess: false, cprInProgress: true, bvm: true, tourniquet: null },
    },
    pathologies: [
      { type: 'cardiacArrest', params: { initialRhythm: 'vfib', noFlowMin: 1, lowFlowMin: 10 }, onsetMinutesBeforeArrival: 11 },
      { type: 'myocardialIschemia', params: { territory: 'lad', occlusion: 0.9, collateral: 0.15 }, onsetMinutesBeforeArrival: 12 },
    ],
    patientKnowledge: { story: 'Unconscious — cannot speak.', symptoms: [], ifAsked: [], conceals: [], personality: 'unresponsive' },
    learningObjectives: ['Deliver high-quality CPR with minimal interruptions', 'Rhythm checks every 2 minutes; defibrillate shockable rhythms promptly', 'Adrenaline and amiodarone timing', 'Recognise ROSC and begin post-resuscitation care'],
    keyEvidence: ['VF on monitor', 'EtCO2 rise with ROSC'],
    debriefNotes: ['Defibrillation success in this simulator depends on myocardial energetic state, which declines with no-flow time and is partly preserved by good CPR (coronary perfusion pressure).'],
  },
  {
    id: 'missed-dialysis',
    title: 'Weak and nauseous',
    tagline: 'Adult on a dialysis programme feeling weak and nauseous',
    category: 'metabolic',
    difficulty: 3,
    hiddenDiagnosis: 'Severe hyperkalaemia after missed haemodialysis',
    diagnosisKeywords: ['hyperkalaemia', 'hyperkalemia', 'high potassium', 'hyper k'],
    differentials: ['Uraemia', 'Acute coronary syndrome', 'Fluid overload', 'Digoxin toxicity'],
    patient: { ageRange: [40, 75], sex: 'any', requiredHistory: ['esrd'] },
    presentation: {
      handoff:
        '{age}-year-old {sex} who normally has dialysis three times a week but missed the last two sessions. Generalised weakness, nausea, feels heavy in the legs. Heart rate a bit slow on our monitor.',
      chiefComplaint: 'Weakness',
    },
    pathologies: [{ type: 'hyperkalemia', params: { initialK: 7.3, riseMmolPerHour: 0.5 }, onsetMinutesBeforeArrival: 0 }],
    patientKnowledge: {
      story: 'Missed two dialysis sessions because of a transport problem. Feels weak, heavy legs, nauseous, a bit breathless.',
      symptoms: ['weak', 'heavy legs', 'nausea', 'palpitations'],
      ifAsked: ['On haemodialysis for 3 years via a left arm fistula', 'Makes very little urine', 'Last dialysis 5 days ago'],
      conceals: [],
      personality: 'tired, cooperative',
    },
    authoredFindings: { exam: [{ zone: 'leftArm', finding: 'Arteriovenous fistula in the left forearm with a palpable thrill — avoid cannulation/BP cuff on this arm' }] },
    learningObjectives: ['Recognise ECG changes of hyperkalaemia', 'Stabilise the myocardium with IV calcium', 'Shift potassium into cells (insulin–dextrose, salbutamol)', 'Arrange definitive removal (dialysis)'],
    keyEvidence: ['Peaked T waves / broad QRS', 'K+ > 6.5 on blood gas'],
    debriefNotes: ['Calcium in this simulator raises the arrhythmia threshold but does not change the serum potassium.'],
  },
  {
    id: 'gastro-elderly',
    title: 'Diarrhoea and vomiting',
    tagline: 'Older adult with several days of diarrhoea, now very weak',
    category: 'metabolic',
    difficulty: 2,
    hiddenDiagnosis: 'Severe hypovolaemia (dehydration) from gastroenteritis with acute kidney injury',
    diagnosisKeywords: ['dehydration', 'hypovolaemia', 'hypovolemia', 'gastroenteritis', 'volume depletion', 'aki'],
    differentials: ['Sepsis', 'Adrenal crisis', 'GI bleed', 'Bowel obstruction'],
    patient: { ageRange: [72, 92], sex: 'any', forbiddenHistory: ['heartFailure'] },
    presentation: {
      handoff:
        '{age}-year-old {sex} with four days of watery diarrhoea and vomiting, hardly eating or drinking. Found on the floor by a neighbour, too weak to get up. Dry mouth. Not passing much urine.',
      chiefComplaint: 'Weak, diarrhoea',
    },
    pathologies: [{ type: 'dehydration', params: { deficitMl: 4200, ongoingLossMlH: 150, diarrhoea: true }, onsetMinutesBeforeArrival: 60 }],
    patientKnowledge: {
      story: 'Diarrhoea many times a day for four days after a family meal. Could not keep fluids down. Legs gave way this morning.',
      symptoms: ['weak', 'dizzy on standing', 'dry mouth', 'crampy tummy'],
      ifAsked: ['Takes blood pressure tablets', 'Not passed urine since yesterday'],
      conceals: [],
      personality: 'weak, slightly muddled',
    },
    learningObjectives: ['Assess volume status clinically and with POCUS', 'Resuscitate with balanced crystalloid in boluses with reassessment', 'Recognise pre-renal AKI and electrolyte disturbance'],
    keyEvidence: ['Tachycardia, low BP', 'Collapsing IVC', 'Raised urea:creatinine ratio', 'Low potassium, normal anion gap acidosis'],
    debriefNotes: ['Diarrhoeal losses in this simulator carry bicarbonate and potassium, producing a normal-anion-gap acidosis; large volumes of 0.9% saline add a hyperchloraemic component.'],
  },
  {
    id: 'found-outside-cold',
    title: 'Found outdoors',
    tagline: 'Adult found outdoors on a winter night',
    category: 'environmental',
    difficulty: 3,
    hiddenDiagnosis: 'Moderate accidental hypothermia',
    diagnosisKeywords: ['hypothermia', 'hypothermic', 'cold exposure'],
    differentials: ['Intoxication', 'Hypoglycaemia', 'Head injury', 'Sepsis', 'Hypothyroidism'],
    patient: { ageRange: [35, 75], sex: 'any', social: { alcohol: 'heavy' }, unknownIdentity: true },
    presentation: {
      handoff:
        'Unknown {sex}, approximately {age}, found lying in a park on a freezing night. Wet clothes. Drowsy and mumbling. Very cold to touch. Unknown how long {pronoun} was there.',
      chiefComplaint: 'Found outside, drowsy',
      ambientC: 22,
    },
    pathologies: [{ type: 'hypothermia', params: { coreC: 30.6, ambientC: 2 }, onsetMinutesBeforeArrival: 20 }],
    patientKnowledge: {
      story: 'Had been drinking, sat down in the park and fell asleep. Very cold.',
      symptoms: ['cold', 'sleepy'],
      ifAsked: ['Drinks heavily', 'Homeless for 6 months'],
      conceals: ['Minimises alcohol intake'],
      personality: 'slurred, slow, confused',
    },
    learningObjectives: ['Measure core temperature', 'Handle the patient gently; recognise arrhythmia risk', 'Rewarm actively (forced air, warmed fluids)', 'Understand altered drug handling in hypothermia'],
    keyEvidence: ['Core temp < 32 °C', 'Bradycardia', 'Reduced consciousness'],
    debriefNotes: ['Hypothermia in the simulator slows drug metabolism, shifts the oxyhaemoglobin curve left, impairs coagulation and increases VF risk below ~30 °C.'],
  },
  {
    id: 'irregular-racing',
    title: 'Breathless and fluttery',
    tagline: 'Older adult with palpitations and breathlessness',
    category: 'cardiovascular',
    difficulty: 2,
    hiddenDiagnosis: 'Atrial fibrillation with rapid ventricular response',
    diagnosisKeywords: ['atrial fibrillation', 'af', 'afib', 'af with rvr', 'rapid ventricular response'],
    differentials: ['Atrial flutter', 'Sinus tachycardia (sepsis)', 'Thyrotoxicosis', 'Pulmonary embolism'],
    patient: { ageRange: [60, 85], sex: 'any', forbiddenHistory: ['heartFailure'] },
    presentation: {
      handoff:
        '{age}-year-old {sex} with a day of fluttering in the chest and increasing breathlessness. Pulse fast and irregular on our monitor. Otherwise well recently.',
      chiefComplaint: 'Palpitations',
    },
    pathologies: [{ type: 'arrhythmia', params: { kind: 'afib' }, onsetMinutesBeforeArrival: 240 }],
    patientKnowledge: {
      story: 'Since yesterday evening heart fluttering and irregular, breathless climbing stairs, tired.',
      symptoms: ['fluttering heart', 'breathless', 'tired'],
      ifAsked: ['Had a glass of wine last night', 'No chest pain'],
      conceals: [],
      personality: 'worried, coherent',
    },
    learningObjectives: ['Recognise irregularly irregular narrow-complex tachycardia', 'Choose rate control vs rhythm control', 'Recognise adverse features requiring cardioversion'],
    keyEvidence: ['Irregularly irregular rhythm without P waves', 'Rate 140–170'],
    debriefNotes: ['Rate control agents in the simulator slow AV-nodal conduction; diltiazem is also a vasodilator and negative inotrope.'],
  },
];

export const SCENARIOS: ScenarioDefinition[] = RAW.map((r) => ScenarioSchema.parse(r) as unknown as ScenarioDefinition);

export function getScenario(id: string): ScenarioDefinition | undefined {
  return SCENARIOS.find((s) => s.id === id);
}
