import type { DrugDef, DoseUnitDef, RateUnitDef } from './types';

/**
 * Drug library.
 *
 * PK/PD parameters are *educational approximations* assembled from typical
 * published adult values (population PK models where they exist: Marsh
 * propofol, Scott & Stanski fentanyl ke0, Clutter 1980 / Simons 2001
 * epinephrine concentrations, standard pharmacology references such as
 * Goodman & Gilman and Katzung for volumes/half-lives). They are tuned so
 * that typical doses produce plausible magnitudes and time courses in the
 * simulator. They are NOT validated for real-world dosing and must never be
 * used for clinical decisions.
 */

const MASS: DoseUnitDef[] = [
  { unit: 'mg', toAmount: 1000 },
  { unit: 'mcg', toAmount: 1 },
  { unit: 'g', toAmount: 1_000_000 },
];

const RATE_MCG: RateUnitDef[] = [
  { unit: 'mcg/kg/min', toAmountPerMin: 1, perKg: true },
  { unit: 'mcg/min', toAmountPerMin: 1 },
  { unit: 'mg/h', toAmountPerMin: 1000 / 60 },
];

export const DRUGS: DrugDef[] = [
  // ------------------------------------------------------------ vasoactive
  {
    id: 'epinephrine',
    name: 'Epinephrine (adrenaline)',
    drugClass: 'Catecholamine (α/β agonist)',
    category: 'resuscitation',
    amountUnit: 'mcg',
    routes: [
      { route: 'IV', F: 1 },
      { route: 'IO', F: 1 },
      { route: 'IM', F: 0.85, ka: 0.13, perfusionDependent: true },
      { route: 'NEB', F: 0.2, ka: 0.2, lungDeposition: 0.1 },
    ],
    doseUnits: MASS,
    defaultDose: { amount: 0.5, unit: 'mg', route: 'IM' },
    typicalDose: 'IM 0.3–0.5 mg (anaphylaxis); IV 1 mg q3–5 min (cardiac arrest)',
    infusion: { units: RATE_MCG, defaultRate: 0.05, defaultUnit: 'mcg/kg/min', typical: '0.02–0.5 mcg/kg/min' },
    pk: { v1: 0.15, v2: 0, q: 0, cl: 0.045, renalFraction: 0.05, hepaticFraction: 0.3, ke0: 1.0 },
    effects: [
      { channel: 'beta1', ec50: 2.5, emax: 1, gamma: 1.2 },
      { channel: 'beta2', ec50: 1.2, emax: 1, gamma: 1.1 },
      { channel: 'alpha1', ec50: 10, emax: 1, gamma: 1.3 },
      { channel: 'beta2Airway', ec50: 60, emax: 1, gamma: 1, local: true },
    ],
    notes: 'Low concentrations are β-dominant (↑HR, ↑contractility, β2 vasodilation, bronchodilation, mast-cell stabilisation). High concentrations add α1 vasoconstriction. IM absorption depends on muscle perfusion.',
    basis: 't½ ≈ 2–3 min; IM thigh 0.3 mg peak ≈ 12 ng/mL at ~8 min (Simons 2001).',
  },
  {
    id: 'norepinephrine',
    name: 'Norepinephrine (noradrenaline)',
    drugClass: 'Catecholamine (α1 ≫ β1)',
    category: 'vasoactive',
    amountUnit: 'mcg',
    routes: [{ route: 'IV', F: 1 }, { route: 'IO', F: 1 }],
    doseUnits: MASS,
    infusion: { units: RATE_MCG, defaultRate: 0.1, defaultUnit: 'mcg/kg/min', typical: '0.05–0.5 mcg/kg/min' },
    pk: { v1: 0.12, v2: 0, q: 0, cl: 0.04, renalFraction: 0.05, hepaticFraction: 0.3, ke0: 1.0 },
    effects: [
      { channel: 'alpha1', ec50: 4, emax: 1, gamma: 1.3 },
      { channel: 'beta1', ec50: 7, emax: 0.6, gamma: 1.1 },
    ],
    notes: 'Predominant arterial and venous vasoconstrictor with modest inotropy. Continuous infusion only in this simulator.',
    basis: 't½ ≈ 2 min; clearance ≈ 3 L/min.',
  },
  {
    id: 'phenylephrine',
    name: 'Phenylephrine',
    drugClass: 'Pure α1 agonist',
    category: 'vasoactive',
    amountUnit: 'mcg',
    routes: [{ route: 'IV', F: 1 }, { route: 'IO', F: 1 }],
    doseUnits: MASS,
    defaultDose: { amount: 100, unit: 'mcg', route: 'IV' },
    typicalDose: 'IV 50–200 mcg bolus',
    infusion: { units: RATE_MCG, defaultRate: 0.5, defaultUnit: 'mcg/kg/min', typical: '0.5–2 mcg/kg/min' },
    pk: { v1: 0.3, v2: 1.5, q: 0.05, cl: 0.03, renalFraction: 0.1, hepaticFraction: 0.6, ke0: 0.5 },
    effects: [{ channel: 'alpha1', ec50: 10, emax: 1, gamma: 1.3 }],
    notes: 'Raises SVR and venous tone; baroreflex slows the heart. No inotropy.',
    basis: 'Pressor effect of a 100 mcg bolus lasts ≈10–15 min.',
  },
  {
    id: 'vasopressin',
    name: 'Vasopressin',
    drugClass: 'V1 receptor agonist',
    category: 'vasoactive',
    amountUnit: 'U',
    routes: [{ route: 'IV', F: 1 }, { route: 'IO', F: 1 }],
    doseUnits: [{ unit: 'units', toAmount: 1 }],
    infusion: { units: [{ unit: 'units/min', toAmountPerMin: 1 }, { unit: 'units/h', toAmountPerMin: 1 / 60 }], defaultRate: 0.03, defaultUnit: 'units/min', typical: '0.03–0.04 units/min' },
    pk: { v1: 0.14, v2: 0, q: 0, cl: 0.0065, renalFraction: 0.3, hepaticFraction: 0.5, ke0: 0.5 },
    effects: [{ channel: 'v1', ec50: 0.08, emax: 1, gamma: 1.5 }],
    notes: 'Catecholamine-independent vasoconstriction; effective in acidosis.',
    basis: 't½ ≈ 10–20 min.',
  },
  {
    id: 'dobutamine',
    name: 'Dobutamine',
    drugClass: 'β1 agonist (inotrope)',
    category: 'vasoactive',
    amountUnit: 'mcg',
    routes: [{ route: 'IV', F: 1 }, { route: 'IO', F: 1 }],
    doseUnits: MASS,
    infusion: { units: RATE_MCG, defaultRate: 5, defaultUnit: 'mcg/kg/min', typical: '2.5–20 mcg/kg/min' },
    pk: { v1: 0.2, v2: 0, q: 0, cl: 0.06, renalFraction: 0.05, hepaticFraction: 0.5, ke0: 0.4 },
    effects: [
      { channel: 'beta1', ec50: 80, emax: 1, gamma: 1.2 },
      { channel: 'beta2', ec50: 250, emax: 0.6, gamma: 1 },
    ],
    notes: 'Increases contractility; mild β2 vasodilation can lower BP.',
    basis: 't½ ≈ 2 min.',
  },
  {
    id: 'isoproterenol',
    name: 'Isoproterenol (isoprenaline)',
    drugClass: 'Non-selective β agonist',
    category: 'vasoactive',
    amountUnit: 'mcg',
    routes: [{ route: 'IV', F: 1 }],
    doseUnits: MASS,
    infusion: { units: [{ unit: 'mcg/min', toAmountPerMin: 1 }], defaultRate: 2, defaultUnit: 'mcg/min', typical: '1–10 mcg/min' },
    pk: { v1: 0.15, v2: 0, q: 0, cl: 0.035, renalFraction: 0.1, hepaticFraction: 0.4, ke0: 0.8 },
    effects: [
      { channel: 'beta1', ec50: 0.6, emax: 1, gamma: 1.2 },
      { channel: 'beta2', ec50: 0.4, emax: 1, gamma: 1.1 },
    ],
    notes: 'Chronotrope — accelerates escape pacemakers modestly in complete heart block.',
    basis: 't½ ≈ 2–5 min.',
  },
  // ------------------------------------------------------------ antiarrhythmics
  {
    id: 'adenosine',
    name: 'Adenosine',
    drugClass: 'A1 agonist (transient AV block)',
    category: 'antiarrhythmic',
    amountUnit: 'mcg',
    routes: [{ route: 'IV', F: 1 }, { route: 'IO', F: 0.6 }],
    doseUnits: MASS,
    defaultDose: { amount: 6, unit: 'mg', route: 'IV' },
    typicalDose: '6 mg rapid IV push, then 12 mg',
    pk: { v1: 0.04, v2: 0, q: 0, cl: 0.166, renalFraction: 0, hepaticFraction: 0, ke0: 6 },
    effects: [{ channel: 'adenosine', ec50: 420, emax: 1, gamma: 2 }],
    notes: 'Plasma half-life < 10 s. Terminates AV-node-dependent re-entry; causes a brief pause and a transient sense of doom/flushing. Does not convert AF or VT.',
    basis: 'Erythrocyte/endothelial uptake; t½ ≈ 10 s.',
  },
  {
    id: 'amiodarone',
    name: 'Amiodarone',
    drugClass: 'Class III antiarrhythmic',
    category: 'antiarrhythmic',
    amountUnit: 'mcg',
    routes: [{ route: 'IV', F: 1 }, { route: 'IO', F: 1 }],
    doseUnits: MASS,
    defaultDose: { amount: 300, unit: 'mg', route: 'IV' },
    typicalDose: '300 mg IV (arrest); 150 mg over 10 min (VT with pulse)',
    infusion: { units: [{ unit: 'mg/min', toAmountPerMin: 1000 }, { unit: 'mg/h', toAmountPerMin: 1000 / 60 }], defaultRate: 1, defaultUnit: 'mg/min' },
    pk: { v1: 0.2, v2: 5, q: 0.02, cl: 0.002, renalFraction: 0, hepaticFraction: 1, ke0: 0.15 },
    effects: [{ channel: 'amiodarone', ec50: 900, emax: 1, gamma: 1.2 }],
    notes: 'Reduces ventricular arrhythmia hazard, improves defibrillation success, slows AV conduction; vasodilation/hypotension with rapid injection.',
    basis: 'Very large Vd; acute effects modelled with a truncated two-compartment model.',
  },
  {
    id: 'diltiazem',
    name: 'Diltiazem',
    drugClass: 'Non-dihydropyridine Ca2+ channel blocker',
    category: 'antiarrhythmic',
    amountUnit: 'mcg',
    routes: [{ route: 'IV', F: 1 }],
    doseUnits: MASS,
    defaultDose: { amount: 15, unit: 'mg', route: 'IV' },
    typicalDose: '0.25 mg/kg IV over 2 min',
    pk: { v1: 0.5, v2: 3, q: 0.03, cl: 0.012, renalFraction: 0, hepaticFraction: 1, ke0: 0.3 },
    effects: [{ channel: 'ccb', ec50: 90, emax: 1, gamma: 1.2 }],
    notes: 'Slows AV-nodal conduction (rate control in AF), vasodilates, negative inotrope.',
    basis: 't½ ≈ 3–4 h.',
  },
  {
    id: 'metoprolol',
    name: 'Metoprolol',
    drugClass: 'β1-selective blocker',
    category: 'antiarrhythmic',
    amountUnit: 'mcg',
    routes: [{ route: 'IV', F: 1 }, { route: 'PO', F: 0.5, ka: 0.03, requiresSwallow: true }],
    doseUnits: MASS,
    defaultDose: { amount: 5, unit: 'mg', route: 'IV' },
    typicalDose: '2.5–5 mg IV slowly, repeat to 15 mg',
    pk: { v1: 0.6, v2: 3.4, q: 0.03, cl: 0.013, renalFraction: 0.05, hepaticFraction: 0.95, ke0: 0.1 },
    effects: [
      { channel: 'beta1', ec50: 1, emax: 0, gamma: 1, antagonistKi: 20 },
      { channel: 'beta2', ec50: 1, emax: 0, gamma: 1, antagonistKi: 250 },
    ],
    notes: 'Competitive antagonist: blunts endogenous and exogenous β1 stimulation. Cardioselectivity is relative.',
    basis: 't½ ≈ 3–4 h.',
  },
  {
    id: 'atropine',
    name: 'Atropine',
    drugClass: 'Muscarinic antagonist',
    category: 'resuscitation',
    amountUnit: 'mcg',
    routes: [{ route: 'IV', F: 1 }, { route: 'IO', F: 1 }, { route: 'IM', F: 0.9, ka: 0.15, perfusionDependent: true }],
    doseUnits: MASS,
    defaultDose: { amount: 1, unit: 'mg', route: 'IV' },
    typicalDose: '0.5–1 mg IV, max 3 mg',
    pk: { v1: 0.3, v2: 2.0, q: 0.05, cl: 0.008, renalFraction: 0.5, hepaticFraction: 0.5, ke0: 0.5 },
    effects: [{ channel: 'muscarinicBlock', ec50: 3, emax: 1, gamma: 1.3 }],
    notes: 'Removes vagal tone at the SA/AV node. Ineffective for infranodal complete heart block (escape rhythm is not vagally controlled).',
    basis: 'Full vagolysis ≈ 0.04 mg/kg.',
  },
  // ------------------------------------------------------------ analgesia / sedation
  {
    id: 'morphine',
    name: 'Morphine',
    drugClass: 'μ-opioid agonist',
    category: 'analgesia-sedation',
    amountUnit: 'mcg',
    routes: [
      { route: 'IV', F: 1 },
      { route: 'IM', F: 1, ka: 0.1, perfusionDependent: true },
      { route: 'SC', F: 1, ka: 0.06, perfusionDependent: true },
    ],
    doseUnits: MASS,
    defaultDose: { amount: 4, unit: 'mg', route: 'IV' },
    typicalDose: '2–5 mg IV titrated',
    pk: { v1: 0.25, v2: 2.5, q: 0.03, cl: 0.017, renalFraction: 0.3, hepaticFraction: 0.7, ke0: 0.04 },
    effects: [{ channel: 'mu', ec50: 22, emax: 1, gamma: 1.3 }],
    notes: 'Slow effect-site equilibration (peak ≈ 15–20 min). Active glucuronide accumulates in renal impairment (approximated via renal clearance fraction).',
    basis: 'CL ≈ 1.2 L/min, Vss ≈ 3 L/kg; t½ke0 ≈ 17 min.',
  },
  {
    id: 'fentanyl',
    name: 'Fentanyl',
    drugClass: 'μ-opioid agonist',
    category: 'analgesia-sedation',
    amountUnit: 'mcg',
    routes: [
      { route: 'IV', F: 1 },
      { route: 'IN', F: 0.7, ka: 0.15 },
    ],
    doseUnits: MASS,
    defaultDose: { amount: 50, unit: 'mcg', route: 'IV' },
    typicalDose: '25–100 mcg IV (1 mcg/kg)',
    infusion: { units: [{ unit: 'mcg/h', toAmountPerMin: 1 / 60 }, { unit: 'mcg/kg/h', toAmountPerMin: 1 / 60, perKg: true }], defaultRate: 50, defaultUnit: 'mcg/h' },
    pk: { v1: 0.18, v2: 3.5, q: 0.07, cl: 0.011, renalFraction: 0.05, hepaticFraction: 0.95, flowLimited: true, ke0: 0.147 },
    effects: [{ channel: 'mu', ec50: 1.1, emax: 1, gamma: 1.3 }],
    notes: 'Rapid onset (t½ke0 ≈ 5 min). Highly lipophilic; redistribution terminates single-dose effect.',
    basis: 'Scott & Stanski ke0 0.147/min; CL ≈ 0.8 L/min.',
  },
  {
    id: 'ketamine',
    name: 'Ketamine',
    drugClass: 'NMDA antagonist (dissociative)',
    category: 'analgesia-sedation',
    amountUnit: 'mcg',
    routes: [
      { route: 'IV', F: 1 },
      { route: 'IM', F: 0.93, ka: 0.2, perfusionDependent: true },
      { route: 'IN', F: 0.45, ka: 0.15 },
    ],
    doseUnits: MASS,
    defaultDose: { amount: 100, unit: 'mg', route: 'IV' },
    typicalDose: 'Induction 1–2 mg/kg IV; analgesia 0.1–0.3 mg/kg',
    pk: { v1: 0.4, v2: 2.5, q: 0.06, cl: 0.017, renalFraction: 0.05, hepaticFraction: 0.95, ke0: 0.3 },
    effects: [{ channel: 'nmda', ec50: 900, emax: 1, gamma: 1.5 }],
    notes: 'Dissociative anaesthesia with preserved respiratory drive and airway reflexes (mostly); sympathomimetic; bronchodilator.',
    basis: 'CL ≈ 1.2 L/min; anaesthetic Cp ≈ 0.7–2 mcg/mL.',
  },
  {
    id: 'midazolam',
    name: 'Midazolam',
    drugClass: 'Benzodiazepine (GABA-A modulator)',
    category: 'analgesia-sedation',
    amountUnit: 'mcg',
    routes: [
      { route: 'IV', F: 1 },
      { route: 'IM', F: 0.9, ka: 0.1, perfusionDependent: true },
      { route: 'IN', F: 0.6, ka: 0.15 },
    ],
    doseUnits: MASS,
    defaultDose: { amount: 2, unit: 'mg', route: 'IV' },
    typicalDose: '1–2.5 mg IV titrated; 10 mg IM (seizure)',
    pk: { v1: 0.3, v2: 0.8, q: 0.02, cl: 0.0055, renalFraction: 0.05, hepaticFraction: 0.95, ke0: 0.15 },
    effects: [{ channel: 'gaba', ec50: 110, emax: 1, gamma: 1.4 }],
    notes: 'Sedation, anticonvulsant. Respiratory depression is modest alone but synergistic with opioids.',
    basis: 'CL ≈ 0.4 L/min; t½ 2–3 h.',
  },
  {
    id: 'lorazepam',
    name: 'Lorazepam',
    drugClass: 'Benzodiazepine (GABA-A modulator)',
    category: 'analgesia-sedation',
    amountUnit: 'mcg',
    routes: [{ route: 'IV', F: 1 }, { route: 'IM', F: 0.95, ka: 0.05, perfusionDependent: true }],
    doseUnits: MASS,
    defaultDose: { amount: 4, unit: 'mg', route: 'IV' },
    typicalDose: '4 mg IV (status epilepticus)',
    pk: { v1: 0.6, v2: 0.7, q: 0.02, cl: 0.0012, renalFraction: 0.05, hepaticFraction: 0.95, ke0: 0.06 },
    effects: [{ channel: 'gaba', ec50: 35, emax: 1, gamma: 1.4 }],
    notes: 'Slower onset than midazolam, long duration.',
    basis: 't½ ≈ 12–15 h.',
  },
  {
    id: 'propofol',
    name: 'Propofol',
    drugClass: 'GABA-A agonist (IV anaesthetic)',
    category: 'analgesia-sedation',
    amountUnit: 'mcg',
    routes: [{ route: 'IV', F: 1 }],
    doseUnits: MASS,
    defaultDose: { amount: 100, unit: 'mg', route: 'IV' },
    typicalDose: 'Induction 1–2 mg/kg (reduce in shock)',
    infusion: { units: [{ unit: 'mcg/kg/min', toAmountPerMin: 1, perKg: true }, { unit: 'mg/h', toAmountPerMin: 1000 / 60 }], defaultRate: 30, defaultUnit: 'mcg/kg/min' },
    pk: { v1: 0.228, v2: 0.464, q: 0.0255, cl: 0.0271, renalFraction: 0, hepaticFraction: 0.7, flowLimited: true, ke0: 0.26 },
    effects: [
      { channel: 'gaba', ec50: 3400, emax: 1, gamma: 2.2 },
      { channel: 'propofolCV', ec50: 3800, emax: 1, gamma: 1.5 },
    ],
    notes: 'Causes apnoea at induction doses; vasodilation and negative inotropy — profound hypotension in hypovolaemic patients.',
    basis: 'Marsh model (V1 0.228 L/kg, k10 0.119, k12 0.112, k21 0.055 /min), ke0 0.26/min.',
  },
  {
    id: 'rocuronium',
    name: 'Rocuronium',
    drugClass: 'Non-depolarising neuromuscular blocker',
    category: 'airway',
    amountUnit: 'mcg',
    routes: [{ route: 'IV', F: 1 }, { route: 'IO', F: 1 }],
    doseUnits: MASS,
    defaultDose: { amount: 100, unit: 'mg', route: 'IV' },
    typicalDose: '1.2 mg/kg IV (RSI)',
    pk: { v1: 0.05, v2: 0.15, q: 0.01, cl: 0.004, renalFraction: 0.3, hepaticFraction: 0.7, ke0: 0.17 },
    effects: [{ channel: 'nmBlock', ec50: 1200, emax: 1, gamma: 4 }],
    notes: 'Complete paralysis — the patient cannot breathe or protect the airway. No sedation or analgesia.',
    basis: 'Onset ≈ 60–90 s at 1.2 mg/kg.',
  },
  {
    id: 'succinylcholine',
    name: 'Succinylcholine (suxamethonium)',
    drugClass: 'Depolarising neuromuscular blocker',
    category: 'airway',
    amountUnit: 'mcg',
    routes: [{ route: 'IV', F: 1 }],
    doseUnits: MASS,
    defaultDose: { amount: 100, unit: 'mg', route: 'IV' },
    typicalDose: '1–1.5 mg/kg IV',
    pk: { v1: 0.04, v2: 0, q: 0, cl: 0.1, renalFraction: 0, hepaticFraction: 0, ke0: 0.25 },
    effects: [{ channel: 'nmBlock', ec50: 2600, emax: 1, gamma: 4 }],
    notes: 'Short-acting paralysis (≈8–10 min). Releases potassium (+≈0.5 mmol/L) — dangerous in hyperkalaemia.',
    basis: 'Plasma cholinesterase hydrolysis.',
  },
  {
    id: 'naloxone',
    name: 'Naloxone',
    drugClass: 'μ-opioid antagonist',
    category: 'resuscitation',
    amountUnit: 'mcg',
    routes: [
      { route: 'IV', F: 1 },
      { route: 'IO', F: 1 },
      { route: 'IM', F: 0.9, ka: 0.12, perfusionDependent: true },
      { route: 'IN', F: 0.45, ka: 0.1 },
    ],
    doseUnits: MASS,
    defaultDose: { amount: 0.4, unit: 'mg', route: 'IV' },
    typicalDose: '0.04–0.4 mg IV titrated; 2 mg IN',
    pk: { v1: 0.8, v2: 2.0, q: 0.05, cl: 0.03, renalFraction: 0.05, hepaticFraction: 0.95, ke0: 0.8 },
    effects: [{ channel: 'mu', ec50: 1, emax: 0, gamma: 1, antagonistKi: 0.45 }],
    notes: 'Competitive antagonist, t½ ≈ 60–90 min — shorter than many opioids, so re-sedation can occur. Large doses in dependent patients precipitate withdrawal.',
    basis: 'CL ≈ 2 L/min, Vss ≈ 2.8 L/kg.',
  },
  // ------------------------------------------------------------ airway / respiratory
  {
    id: 'salbutamol',
    name: 'Salbutamol (albuterol)',
    drugClass: 'β2 agonist',
    category: 'airway',
    amountUnit: 'mcg',
    routes: [
      { route: 'NEB', F: 0.3, ka: 0.08, lungDeposition: 0.12 },
      { route: 'IV', F: 1 },
    ],
    doseUnits: MASS,
    defaultDose: { amount: 5, unit: 'mg', route: 'NEB' },
    typicalDose: 'Neb 2.5–5 mg, repeat/back-to-back',
    infusion: { units: [{ unit: 'mcg/min', toAmountPerMin: 1 }], defaultRate: 5, defaultUnit: 'mcg/min', typical: '5–20 mcg/min' },
    pk: { v1: 0.8, v2: 1.5, q: 0.02, cl: 0.007, renalFraction: 0.6, hepaticFraction: 0.4, ke0: 0.3 },
    effects: [
      { channel: 'beta2', ec50: 12, emax: 1, gamma: 1.1 },
      { channel: 'beta1', ec50: 70, emax: 0.5, gamma: 1 },
      { channel: 'beta2Airway', ec50: 120, emax: 1, gamma: 1, local: true },
    ],
    notes: 'Nebuliser delivery falls when minute ventilation/airflow is very low ("silent chest"). Systemic effects: tachycardia, tremor, hypokalaemia, lactate.',
    basis: 'Lung deposition ≈ 10–15% of nebulised dose.',
  },
  {
    id: 'ipratropium',
    name: 'Ipratropium',
    drugClass: 'Inhaled muscarinic antagonist',
    category: 'airway',
    amountUnit: 'mcg',
    routes: [{ route: 'NEB', F: 0.05, ka: 0.03, lungDeposition: 0.12 }],
    doseUnits: MASS,
    defaultDose: { amount: 500, unit: 'mcg', route: 'NEB' },
    typicalDose: 'Neb 500 mcg',
    pk: { v1: 0.5, v2: 3, q: 0.03, cl: 0.03, renalFraction: 0.5, hepaticFraction: 0.5, ke0: 0.2 },
    effects: [{ channel: 'muscarinicAirway', ec50: 15, emax: 1, gamma: 1, local: true }],
    notes: 'Add-on bronchodilator; minimal systemic absorption.',
    basis: 'Quaternary amine.',
  },
  {
    id: 'magnesium',
    name: 'Magnesium sulfate',
    drugClass: 'Electrolyte / smooth-muscle relaxant',
    category: 'airway',
    amountUnit: 'mmol',
    routes: [{ route: 'IV', F: 1 }, { route: 'IO', F: 1 }],
    doseUnits: [
      { unit: 'g', toAmount: 4.06 },
      { unit: 'mmol', toAmount: 1 },
    ],
    defaultDose: { amount: 2, unit: 'g', route: 'IV' },
    typicalDose: '2 g IV over 20 min',
    effects: [],
    direct: { substance: 'mg' },
    notes: 'Bronchodilation and antiarrhythmic (torsades) effects scale with serum Mg; hypotension if very high.',
    basis: 'MgSO4·7H2O 1 g ≈ 4.06 mmol Mg.',
  },
  {
    id: 'hydrocortisone',
    name: 'Hydrocortisone',
    drugClass: 'Corticosteroid',
    category: 'other',
    amountUnit: 'mcg',
    routes: [{ route: 'IV', F: 1 }, { route: 'IM', F: 0.9, ka: 0.05 }],
    doseUnits: MASS,
    defaultDose: { amount: 200, unit: 'mg', route: 'IV' },
    typicalDose: '100–200 mg IV',
    pk: { v1: 0.4, v2: 0, q: 0, cl: 0.004, renalFraction: 0, hepaticFraction: 1, ke0: 0.005 },
    effects: [{ channel: 'steroid', ec50: 1500, emax: 1, gamma: 1 }],
    notes: 'Genomic anti-inflammatory effect develops over hours (slow ke0 approximates the indirect response). No immediate haemodynamic effect.',
    basis: 'Onset of anti-inflammatory effect 4–6 h.',
  },
  {
    id: 'methylprednisolone',
    name: 'Methylprednisolone',
    drugClass: 'Corticosteroid',
    category: 'other',
    amountUnit: 'mcg',
    routes: [{ route: 'IV', F: 1 }],
    doseUnits: MASS,
    defaultDose: { amount: 125, unit: 'mg', route: 'IV' },
    typicalDose: '40–125 mg IV',
    pk: { v1: 1.2, v2: 0, q: 0, cl: 0.005, renalFraction: 0, hepaticFraction: 1, ke0: 0.005 },
    effects: [{ channel: 'steroid', ec50: 250, emax: 1, gamma: 1 }],
    notes: 'Delayed anti-inflammatory effect.',
    basis: 't½ ≈ 2–3 h; effect delayed.',
  },
  {
    id: 'diphenhydramine',
    name: 'Diphenhydramine',
    drugClass: 'H1 antihistamine',
    category: 'other',
    amountUnit: 'mcg',
    routes: [{ route: 'IV', F: 1 }, { route: 'IM', F: 0.9, ka: 0.08, perfusionDependent: true }, { route: 'PO', F: 0.5, ka: 0.03, requiresSwallow: true }],
    doseUnits: MASS,
    defaultDose: { amount: 50, unit: 'mg', route: 'IV' },
    typicalDose: '25–50 mg IV',
    pk: { v1: 1, v2: 2, q: 0.03, cl: 0.01, renalFraction: 0.1, hepaticFraction: 0.9, ke0: 0.2 },
    effects: [{ channel: 'h1Block', ec50: 25, emax: 1, gamma: 1 }],
    notes: 'Relieves itch/urticaria. Does NOT treat airway oedema, bronchospasm or shock in anaphylaxis. Sedating.',
    basis: 't½ ≈ 4–8 h.',
  },
  {
    id: 'ondansetron',
    name: 'Ondansetron',
    drugClass: '5-HT3 antagonist',
    category: 'other',
    amountUnit: 'mcg',
    routes: [{ route: 'IV', F: 1 }, { route: 'IM', F: 0.9, ka: 0.1 }],
    doseUnits: MASS,
    defaultDose: { amount: 4, unit: 'mg', route: 'IV' },
    typicalDose: '4 mg IV',
    pk: { v1: 1.5, v2: 0, q: 0, cl: 0.006, renalFraction: 0.05, hepaticFraction: 0.95, ke0: 0.2 },
    effects: [{ channel: 'antiemetic', ec50: 15, emax: 0.8, gamma: 1 }],
    notes: 'Reduces nausea and vomiting risk.',
    basis: 't½ ≈ 3–4 h.',
  },
  {
    id: 'paracetamol',
    name: 'Paracetamol (acetaminophen)',
    drugClass: 'Antipyretic analgesic',
    category: 'other',
    amountUnit: 'mcg',
    routes: [{ route: 'IV', F: 1 }, { route: 'PO', F: 0.85, ka: 0.05, requiresSwallow: true }],
    doseUnits: MASS,
    defaultDose: { amount: 1, unit: 'g', route: 'IV' },
    typicalDose: '1 g IV/PO',
    pk: { v1: 0.9, v2: 0, q: 0, cl: 0.005, renalFraction: 0.05, hepaticFraction: 0.95, ke0: 0.03 },
    effects: [{ channel: 'antipyretic', ec50: 9000, emax: 0.9, gamma: 1.2 }],
    notes: 'Lowers the hypothalamic set-point in fever over ≈30–60 min.',
    basis: 't½ ≈ 2–2.5 h.',
  },
  // ------------------------------------------------------------ cardiovascular / haematology
  {
    id: 'aspirin',
    name: 'Aspirin',
    drugClass: 'Antiplatelet (COX inhibitor)',
    category: 'haematology',
    amountUnit: 'mcg',
    routes: [{ route: 'PO', F: 0.7, ka: 0.08, requiresSwallow: true }],
    doseUnits: MASS,
    defaultDose: { amount: 300, unit: 'mg', route: 'PO' },
    typicalDose: '162–325 mg chewed',
    pk: { v1: 0.15, v2: 0, q: 0, cl: 0.009, renalFraction: 0.1, hepaticFraction: 0.9, ke0: 0.1 },
    effects: [{ channel: 'antiplatelet', ec50: 4000, emax: 1, gamma: 1.5 }],
    notes: 'Irreversible platelet inhibition (effect is latched once achieved). Slows thrombus propagation in ACS; increases bleeding.',
    basis: 'Acetylates COX-1 for platelet lifespan.',
  },
  {
    id: 'nitroglycerin',
    name: 'Nitroglycerin (GTN)',
    drugClass: 'Nitrate venodilator',
    category: 'vasoactive',
    amountUnit: 'mcg',
    routes: [{ route: 'SL', F: 0.4, ka: 0.6, requiresSwallow: false }, { route: 'IV', F: 1 }],
    doseUnits: MASS,
    defaultDose: { amount: 400, unit: 'mcg', route: 'SL' },
    typicalDose: 'SL 400 mcg q5 min; IV 10–200 mcg/min',
    infusion: { units: [{ unit: 'mcg/min', toAmountPerMin: 1 }], defaultRate: 20, defaultUnit: 'mcg/min' },
    pk: { v1: 0.3, v2: 0, q: 0, cl: 0.083, renalFraction: 0, hepaticFraction: 0.3, ke0: 0.7 },
    effects: [{ channel: 'nitrate', ec50: 3, emax: 1, gamma: 1 }],
    notes: 'Venodilation lowers preload (and myocardial O2 demand); arteriolar and coronary dilation at higher doses. Dangerous in preload-dependent states (RV infarction, hypovolaemia).',
    basis: 't½ ≈ 2–3 min.',
  },
  {
    id: 'heparin',
    name: 'Heparin (unfractionated)',
    drugClass: 'Anticoagulant',
    category: 'haematology',
    amountUnit: 'U',
    routes: [{ route: 'IV', F: 1 }, { route: 'SC', F: 0.3, ka: 0.01 }],
    doseUnits: [{ unit: 'units', toAmount: 1 }],
    defaultDose: { amount: 5000, unit: 'units', route: 'IV' },
    typicalDose: '60–80 units/kg IV bolus (max ≈5000)',
    infusion: { units: [{ unit: 'units/h', toAmountPerMin: 1 / 60 }, { unit: 'units/kg/h', toAmountPerMin: 1 / 60, perKg: true }], defaultRate: 1000, defaultUnit: 'units/h' },
    pk: { v1: 0.07, v2: 0, q: 0, cl: 0.00065, renalFraction: 0.2, hepaticFraction: 0.8, ke0: 1 },
    effects: [{ channel: 'anticoagulant', ec50: 350, emax: 1, gamma: 1.5 }],
    notes: 'Prolongs aPTT; slows coronary thrombus propagation; increases bleeding.',
    basis: 't½ ≈ 60–90 min; therapeutic anti-Xa ≈ 0.3–0.7 U/mL.',
  },
  {
    id: 'tenecteplase',
    name: 'Tenecteplase',
    drugClass: 'Fibrinolytic',
    category: 'haematology',
    amountUnit: 'mcg',
    routes: [{ route: 'IV', F: 1 }],
    doseUnits: MASS,
    defaultDose: { amount: 40, unit: 'mg', route: 'IV' },
    typicalDose: '30–50 mg IV (weight-based)',
    pk: { v1: 0.06, v2: 0, q: 0, cl: 0.0015, renalFraction: 0, hepaticFraction: 1, ke0: 0.5 },
    effects: [{ channel: 'fibrinolytic', ec50: 2500, emax: 1, gamma: 1.5 }],
    notes: 'Lyses coronary thrombus with a probability that falls with time from symptom onset; markedly worsens any active haemorrhage.',
    basis: 't½ ≈ 20–25 min.',
  },
  {
    id: 'tranexamic',
    name: 'Tranexamic acid',
    drugClass: 'Antifibrinolytic',
    category: 'haematology',
    amountUnit: 'mcg',
    routes: [{ route: 'IV', F: 1 }],
    doseUnits: MASS,
    defaultDose: { amount: 1, unit: 'g', route: 'IV' },
    typicalDose: '1 g IV over 10 min',
    pk: { v1: 0.2, v2: 0, q: 0, cl: 0.0015, renalFraction: 0.9, hepaticFraction: 0.1, ke0: 0.1 },
    effects: [{ channel: 'antifibrinolytic', ec50: 10000, emax: 1, gamma: 1 }],
    notes: 'Modest reduction in bleeding rate when given early in traumatic haemorrhage.',
    basis: 'Renally cleared; t½ ≈ 2 h.',
  },
  {
    id: 'furosemide',
    name: 'Furosemide',
    drugClass: 'Loop diuretic',
    category: 'other',
    amountUnit: 'mcg',
    routes: [{ route: 'IV', F: 1 }],
    doseUnits: MASS,
    defaultDose: { amount: 40, unit: 'mg', route: 'IV' },
    typicalDose: '20–80 mg IV',
    pk: { v1: 0.11, v2: 0, q: 0, cl: 0.002, renalFraction: 0.7, hepaticFraction: 0.3, ke0: 0.1 },
    effects: [{ channel: 'diuretic', ec50: 900, emax: 1, gamma: 1.2 }],
    notes: 'Natriuresis proportional to delivered drug and GFR; causes potassium loss and volume depletion.',
    basis: 't½ ≈ 1–1.5 h.',
  },
  // ------------------------------------------------------------ metabolic (direct chemistry)
  {
    id: 'dextrose50',
    name: 'Dextrose 50% (D50)',
    drugClass: 'Glucose',
    category: 'metabolic',
    amountUnit: 'mmol',
    routes: [{ route: 'IV', F: 1 }, { route: 'IO', F: 1 }],
    doseUnits: [
      { unit: 'mL', toAmount: 2.775 },
      { unit: 'g', toAmount: 5.55 },
    ],
    defaultDose: { amount: 50, unit: 'mL', route: 'IV' },
    typicalDose: '25 g (50 mL D50) IV',
    effects: [],
    direct: { substance: 'glucose', waterPerMmol: 0.36 },
    notes: '25 g raises plasma glucose by ≈ 8–10 mmol/L acutely, then redistributes and is consumed.',
    basis: '1 g glucose = 5.55 mmol.',
  },
  {
    id: 'dextrose10',
    name: 'Dextrose 10% (D10)',
    drugClass: 'Glucose',
    category: 'metabolic',
    amountUnit: 'mmol',
    routes: [{ route: 'IV', F: 1 }, { route: 'IO', F: 1 }],
    doseUnits: [{ unit: 'mL', toAmount: 0.555 }, { unit: 'g', toAmount: 5.55 }],
    defaultDose: { amount: 250, unit: 'mL', route: 'IV' },
    typicalDose: '100–250 mL IV',
    infusion: { units: [{ unit: 'mL/h', toAmountPerMin: 0.555 / 60 }], defaultRate: 100, defaultUnit: 'mL/h' },
    effects: [],
    direct: { substance: 'glucose', waterPerMmol: 1.8 },
    notes: 'Glucose with free water.',
    basis: '100 g/L.',
  },
  {
    id: 'glucoseGel',
    name: 'Oral glucose gel',
    drugClass: 'Glucose',
    category: 'metabolic',
    amountUnit: 'mmol',
    routes: [{ route: 'PO', F: 0.9, ka: 0.06, requiresSwallow: true }],
    doseUnits: [{ unit: 'g', toAmount: 5.55 }],
    defaultDose: { amount: 15, unit: 'g', route: 'PO' },
    typicalDose: '15–20 g PO if able to swallow safely',
    effects: [],
    direct: { substance: 'glucose' },
    notes: 'Only safe if the patient is alert with intact airway reflexes — otherwise aspiration risk.',
    basis: 'Absorbed over ≈15–30 min.',
  },
  {
    id: 'glucagon',
    name: 'Glucagon',
    drugClass: 'Counter-regulatory hormone',
    category: 'metabolic',
    amountUnit: 'mcg',
    routes: [{ route: 'IM', F: 0.8, ka: 0.1, perfusionDependent: true }, { route: 'IV', F: 1 }, { route: 'SC', F: 0.8, ka: 0.07 }],
    doseUnits: MASS,
    defaultDose: { amount: 1, unit: 'mg', route: 'IM' },
    typicalDose: '1 mg IM/IV',
    pk: { v1: 0.25, v2: 0, q: 0, cl: 0.013, renalFraction: 0.3, hepaticFraction: 0.7, ke0: 0.3 },
    effects: [{ channel: 'glucagon', ec50: 1.5, emax: 1, gamma: 1 }],
    notes: 'Mobilises hepatic glycogen — ineffective when glycogen is depleted (alcohol use, starvation, prolonged hypoglycaemia).',
    basis: 't½ ≈ 8–18 min.',
  },
  {
    id: 'insulinRegular',
    name: 'Insulin (regular/soluble)',
    drugClass: 'Insulin',
    category: 'metabolic',
    amountUnit: 'mU',
    routes: [{ route: 'IV', F: 1 }, { route: 'SC', F: 0.8, ka: 0.012 }],
    doseUnits: [{ unit: 'units', toAmount: 1000 }],
    defaultDose: { amount: 10, unit: 'units', route: 'IV' },
    typicalDose: '10 units IV with dextrose (hyperkalaemia); infusion 0.1 units/kg/h (DKA)',
    infusion: { units: [{ unit: 'units/h', toAmountPerMin: 1000 / 60 }, { unit: 'units/kg/h', toAmountPerMin: 1000 / 60, perKg: true }], defaultRate: 0.1, defaultUnit: 'units/kg/h' },
    pk: { v1: 0.1, v2: 0, q: 0, cl: 0.014, renalFraction: 0.35, hepaticFraction: 0.65, ke0: 1 },
    effects: [],
    notes: 'Lowers glucose (with a delay via remote insulin action) and shifts potassium into cells. Plasma t½ ≈ 5 min.',
    basis: 'Vd ≈ 0.1 L/kg; CL ≈ 1 L/min.',
  },
  {
    id: 'potassiumChloride',
    name: 'Potassium chloride',
    drugClass: 'Electrolyte',
    category: 'metabolic',
    amountUnit: 'mmol',
    routes: [{ route: 'IV', F: 1 }, { route: 'PO', F: 0.9, ka: 0.02, requiresSwallow: true }],
    doseUnits: [{ unit: 'mmol', toAmount: 1 }],
    defaultDose: { amount: 20, unit: 'mmol', route: 'PO' },
    typicalDose: 'IV ≤ 10–20 mmol/h via infusion',
    infusion: { units: [{ unit: 'mmol/h', toAmountPerMin: 1 / 60 }], defaultRate: 10, defaultUnit: 'mmol/h', typical: '10–20 mmol/h' },
    effects: [],
    direct: { substance: 'k', companion: { substance: 'cl', ratio: 1 } },
    notes: 'IV potassium must be infused, never pushed — a rapid bolus causes lethal hyperkalaemia in this simulator too.',
    basis: 'Distributes into ECF, then shifts into cells.',
  },
  {
    id: 'calciumGluconate',
    name: 'Calcium gluconate 10%',
    drugClass: 'Electrolyte / membrane stabiliser',
    category: 'metabolic',
    amountUnit: 'mmol',
    routes: [{ route: 'IV', F: 1 }, { route: 'IO', F: 1 }],
    doseUnits: [{ unit: 'mL', toAmount: 0.225 }, { unit: 'mmol', toAmount: 1 }, { unit: 'g', toAmount: 2.25 }],
    defaultDose: { amount: 30, unit: 'mL', route: 'IV' },
    typicalDose: '30 mL 10% IV over 5–10 min',
    effects: [],
    direct: { substance: 'ca' },
    notes: 'Raises ionised calcium; stabilises the myocardium against hyperkalaemia (does not lower potassium).',
    basis: '10% calcium gluconate ≈ 0.225 mmol Ca/mL.',
  },
  {
    id: 'calciumChloride',
    name: 'Calcium chloride 10%',
    drugClass: 'Electrolyte / membrane stabiliser',
    category: 'metabolic',
    amountUnit: 'mmol',
    routes: [{ route: 'IV', F: 1 }, { route: 'IO', F: 1 }],
    doseUnits: [{ unit: 'mL', toAmount: 0.68 }, { unit: 'mmol', toAmount: 1 }],
    defaultDose: { amount: 10, unit: 'mL', route: 'IV' },
    typicalDose: '10 mL 10% IV (central line preferred)',
    effects: [],
    direct: { substance: 'ca', companion: { substance: 'cl', ratio: 2 } },
    notes: 'Three times the calcium of gluconate per mL.',
    basis: '10% CaCl2 ≈ 0.68 mmol Ca/mL.',
  },
  {
    id: 'sodiumBicarbonate',
    name: 'Sodium bicarbonate 8.4%',
    drugClass: 'Alkalinising agent',
    category: 'metabolic',
    amountUnit: 'mmol',
    routes: [{ route: 'IV', F: 1 }, { route: 'IO', F: 1 }],
    doseUnits: [{ unit: 'mL', toAmount: 1 }, { unit: 'mmol', toAmount: 1 }],
    defaultDose: { amount: 50, unit: 'mL', route: 'IV' },
    typicalDose: '50 mmol (50 mL 8.4%) IV',
    effects: [],
    direct: { substance: 'hco3', companion: { substance: 'na', ratio: 1 }, co2PerMmol: 11 },
    notes: 'Buffers acid but generates CO2 that must be exhaled; hypernatraemia with large doses; shifts potassium into cells.',
    basis: '8.4% = 1 mmol/mL.',
  },
  // ------------------------------------------------------------ antimicrobials
  {
    id: 'ceftriaxone',
    name: 'Ceftriaxone',
    drugClass: '3rd-generation cephalosporin',
    category: 'antimicrobial',
    amountUnit: 'mcg',
    allergyClass: 'cephalosporin',
    routes: [{ route: 'IV', F: 1 }, { route: 'IM', F: 1, ka: 0.02 }],
    doseUnits: MASS,
    defaultDose: { amount: 2, unit: 'g', route: 'IV' },
    typicalDose: '1–2 g IV',
    pk: { v1: 0.15, v2: 0, q: 0, cl: 0.00022, renalFraction: 0.5, hepaticFraction: 0.5, ke0: 0.2 },
    effects: [],
    antimicrobial: { spectrum: ['gram-negative-community', 'strep', 'mssa'], micMgL: 1 },
    notes: 'Covers most community Gram-negatives and streptococci; not Pseudomonas, not MRSA.',
    basis: 't½ ≈ 8 h.',
  },
  {
    id: 'piperacillinTazobactam',
    name: 'Piperacillin-tazobactam',
    drugClass: 'Penicillin + β-lactamase inhibitor',
    category: 'antimicrobial',
    amountUnit: 'mcg',
    allergyClass: 'penicillin',
    routes: [{ route: 'IV', F: 1 }],
    doseUnits: MASS,
    defaultDose: { amount: 4.5, unit: 'g', route: 'IV' },
    typicalDose: '4.5 g IV',
    pk: { v1: 0.2, v2: 0, q: 0, cl: 0.0023, renalFraction: 0.7, hepaticFraction: 0.3, ke0: 0.2 },
    effects: [],
    antimicrobial: { spectrum: ['gram-negative-community', 'pseudomonas', 'anaerobe', 'strep', 'mssa'], micMgL: 8 },
    notes: 'Broad-spectrum including Pseudomonas and anaerobes. Penicillin class.',
    basis: 't½ ≈ 1 h.',
  },
  {
    id: 'meropenem',
    name: 'Meropenem',
    drugClass: 'Carbapenem',
    category: 'antimicrobial',
    amountUnit: 'mcg',
    allergyClass: 'carbapenem',
    routes: [{ route: 'IV', F: 1 }],
    doseUnits: MASS,
    defaultDose: { amount: 1, unit: 'g', route: 'IV' },
    typicalDose: '1 g IV',
    pk: { v1: 0.3, v2: 0, q: 0, cl: 0.0035, renalFraction: 0.8, hepaticFraction: 0.2, ke0: 0.2 },
    effects: [],
    antimicrobial: { spectrum: ['gram-negative-community', 'esbl', 'pseudomonas', 'anaerobe', 'strep', 'mssa'], micMgL: 1 },
    notes: 'Very broad Gram-negative spectrum including ESBL producers.',
    basis: 't½ ≈ 1 h.',
  },
  {
    id: 'vancomycin',
    name: 'Vancomycin',
    drugClass: 'Glycopeptide',
    category: 'antimicrobial',
    amountUnit: 'mcg',
    routes: [{ route: 'IV', F: 1 }],
    doseUnits: MASS,
    defaultDose: { amount: 1.5, unit: 'g', route: 'IV' },
    typicalDose: '15–25 mg/kg IV',
    pk: { v1: 0.7, v2: 0, q: 0, cl: 0.0013, renalFraction: 0.9, hepaticFraction: 0.1, ke0: 0.2 },
    effects: [],
    antimicrobial: { spectrum: ['mrsa', 'mssa', 'strep'], micMgL: 1 },
    notes: 'Gram-positive cover including MRSA. No Gram-negative activity.',
    basis: 't½ ≈ 6 h (renal).',
  },
  // ------------------------------------------------------------ exposure-only toxicants
  {
    id: 'heroin',
    name: 'Heroin (diamorphine)',
    drugClass: 'μ-opioid agonist (illicit)',
    category: 'analgesia-sedation',
    amountUnit: 'mcg',
    exposureOnly: true,
    routes: [{ route: 'IV', F: 1 }, { route: 'IN', F: 0.5, ka: 0.1 }],
    doseUnits: MASS,
    pk: { v1: 0.3, v2: 1.2, q: 0.012, cl: 0.009, renalFraction: 0.3, hepaticFraction: 0.7, ke0: 0.12 },
    effects: [{ channel: 'mu', ec50: 12, emax: 1, gamma: 1.3 }],
    notes: 'Rapidly converted to 6-MAM and morphine; modelled as a single morphine-equivalent species with faster onset.',
    basis: 'Morphine-like elimination; potency ≈ 2× morphine.',
  },
  {
    id: 'methadone',
    name: 'Methadone',
    drugClass: 'μ-opioid agonist (long-acting)',
    category: 'analgesia-sedation',
    amountUnit: 'mcg',
    exposureOnly: true,
    routes: [{ route: 'PO', F: 0.8, ka: 0.012 }],
    doseUnits: MASS,
    pk: { v1: 1.0, v2: 3.0, q: 0.02, cl: 0.0018, renalFraction: 0.2, hepaticFraction: 0.8, ke0: 0.05 },
    effects: [{ channel: 'mu', ec50: 70, emax: 1, gamma: 1.3 }],
    notes: 'Half-life 24–36 h — far longer than naloxone.',
    basis: 'Oral bioavailability ≈ 80%.',
  },
  {
    id: 'insulinGlargine',
    name: 'Insulin glargine',
    drugClass: 'Long-acting insulin',
    category: 'metabolic',
    amountUnit: 'mU',
    exposureOnly: true,
    routes: [{ route: 'SC', F: 0.6, ka: 0.0018 }],
    doseUnits: [{ unit: 'units', toAmount: 1000 }],
    pk: { v1: 0.1, v2: 0, q: 0, cl: 0.014, renalFraction: 0.35, hepaticFraction: 0.65, ke0: 1 },
    effects: [],
    notes: 'Slow, prolonged absorption from the subcutaneous depot.',
    basis: 'Flat profile over ≈24 h at therapeutic doses; prolonged in overdose.',
  },
];

export const DRUG_MAP: Record<string, DrugDef> = Object.fromEntries(DRUGS.map((d) => [d.id, d]));

export function getDrug(id: string): DrugDef {
  const d = DRUG_MAP[id];
  if (!d) throw new Error(`Unknown drug: ${id}`);
  return d;
}

export const ORDERABLE_DRUGS = DRUGS.filter((d) => !d.exposureOnly);

// ---------------------------------------------------------------------------
// Fluids and blood products
// ---------------------------------------------------------------------------

export interface FluidDef {
  id: string;
  label: string;
  kind: 'crystalloid' | 'colloid' | 'blood';
  na: number;
  cl: number;
  k: number;
  /** Bicarbonate equivalent after metabolism (lactate/acetate), mmol/L */
  hco3Equivalent: number;
  glucose: number; // mmol/L
  /** Protein g/L */
  protein: number;
  /** Haematocrit of the product (blood) */
  hct: number;
  /** Clotting factor activity of the plasma fraction 0..1 */
  factors: number;
  /** Platelets added per unit (10^9/L rise in a 70 kg adult) */
  plateletsPerUnit: number;
  fibrinogenGL: number;
  unitVolume: number;
  /** Citrate load lowering ionised Ca per unit (mmol/L drop in 70 kg) */
  citrateCaDrop: number;
  notes: string;
}

export const FLUIDS: FluidDef[] = [
  { id: 'ns', label: '0.9% Sodium chloride', kind: 'crystalloid', na: 154, cl: 154, k: 0, hco3Equivalent: 0, glucose: 0, protein: 0, hct: 0, factors: 0, plateletsPerUnit: 0, fibrinogenGL: 0, unitVolume: 1000, citrateCaDrop: 0, notes: 'Supraphysiological chloride — large volumes cause hyperchloraemic acidosis.' },
  { id: 'lr', label: "Lactated Ringer's", kind: 'crystalloid', na: 130, cl: 109, k: 4, hco3Equivalent: 28, glucose: 0, protein: 0, hct: 0, factors: 0, plateletsPerUnit: 0, fibrinogenGL: 0, unitVolume: 1000, citrateCaDrop: 0, notes: 'Balanced crystalloid; lactate is metabolised to bicarbonate.' },
  { id: 'plasmalyte', label: 'Balanced crystalloid (Plasma-Lyte-type)', kind: 'crystalloid', na: 140, cl: 98, k: 5, hco3Equivalent: 27, glucose: 0, protein: 0, hct: 0, factors: 0, plateletsPerUnit: 0, fibrinogenGL: 0, unitVolume: 1000, citrateCaDrop: 0, notes: 'Balanced crystalloid; acetate metabolised to bicarbonate.' },
  { id: 'd5w', label: '5% Dextrose', kind: 'crystalloid', na: 0, cl: 0, k: 0, hco3Equivalent: 0, glucose: 278, protein: 0, hct: 0, factors: 0, plateletsPerUnit: 0, fibrinogenGL: 0, unitVolume: 1000, citrateCaDrop: 0, notes: 'Effectively free water once glucose is metabolised — distributes into all body water; poor volume expander.' },
  { id: 'albumin5', label: '5% Albumin', kind: 'colloid', na: 145, cl: 100, k: 0, hco3Equivalent: 0, glucose: 0, protein: 50, hct: 0, factors: 0, plateletsPerUnit: 0, fibrinogenGL: 0, unitVolume: 500, citrateCaDrop: 0, notes: 'Oncotically active — remains intravascular longer unless capillaries leak.' },
  { id: 'prbc', label: 'Packed red cells (1 unit)', kind: 'blood', na: 110, cl: 90, k: 20, hco3Equivalent: 0, glucose: 20, protein: 20, hct: 0.6, factors: 0.05, plateletsPerUnit: 0, fibrinogenGL: 0.1, unitVolume: 300, citrateCaDrop: 0.03, notes: 'Restores oxygen-carrying capacity; contains almost no clotting factors or platelets.' },
  { id: 'ffp', label: 'Fresh frozen plasma (1 unit)', kind: 'blood', na: 165, cl: 80, k: 4, hco3Equivalent: 0, glucose: 15, protein: 60, hct: 0, factors: 1.0, plateletsPerUnit: 0, fibrinogenGL: 2.5, unitVolume: 250, citrateCaDrop: 0.05, notes: 'Replaces clotting factors and fibrinogen.' },
  { id: 'platelets', label: 'Platelets (1 adult dose)', kind: 'blood', na: 150, cl: 90, k: 4, hco3Equivalent: 0, glucose: 10, protein: 50, hct: 0, factors: 0.7, plateletsPerUnit: 35, fibrinogenGL: 2, unitVolume: 250, citrateCaDrop: 0.04, notes: 'Raises platelet count ≈ 30–40 ×10⁹/L.' },
  { id: 'wholeblood', label: 'Whole blood (1 unit, low-titre O)', kind: 'blood', na: 150, cl: 90, k: 8, hco3Equivalent: 0, glucose: 20, protein: 60, hct: 0.4, factors: 0.8, plateletsPerUnit: 15, fibrinogenGL: 2, unitVolume: 500, citrateCaDrop: 0.05, notes: 'Balanced red cells, plasma and platelets.' },
];

export const FLUID_MAP: Record<string, FluidDef> = Object.fromEntries(FLUIDS.map((f) => [f.id, f]));
